name: 'VisualPinball.NextReleaseAction'
description: 'Action used for determining the next version of VisualPinball.* projects.'
author: 'Jason Millard <jsm174@gmail.com>'
inputs:
  tagPrefix:
    required: false
    description: 'Prefix when tagging the release'
outputs:
  version:
    description: 'Current version in package.json'
  tags:
    description: 'Reverse sorted git tags in semver format'
  nextVersion:
    description: 'Computed next version'
  nextTag:
    description: 'Computed next version with prefix'
  isPrerelease:
    description: 'If true, the version is a pre-release'
runs:
  using: 'node12'
  main: 'dist/index.js'
