name: 'VisualPinball.NextReleaseAction'
description: 'Action used for determining the next version of VisualPinball.* projects.'
author: 'Jason Millard <jsm174@gmail.com>'
inputs:
  path:
    required: false
    description: 'Path to folder containing package.json'
  tagPrefix:
    required: false
    description: 'Prefix when tagging the release'
outputs:
  version:
    description: 'Version in package.json'
  tags:
    description: 'Git tags in semver format'
  nextVersion:
    description: 'Computed next version'
  nextTag:
    description: 'Computed next version with prefix'
  isBump:
    description: 'If true, the computed next version differs from the version in package.json'
  isPrerelease:
    description: 'If true, the version is a pre-release'
runs:
  using: 'node12'
  main: 'dist/index.js'
